apiVersion: v1
kind: Pod
metadata:
  name: model-copy
  namespace: opt-rag
spec:
  restartPolicy: Never
  containers:
  - name: copy
    image: google/cloud-sdk:slim
    command: ["/bin/sh", "-c"]
    args:
      - |
        gsutil -m cp -r gs://opt-rag-bucket-1746746058/models/* /models/ && \
        gsutil -m cp -r gs://opt-rag-bucket-1746746058/vector_store/* /vector_store/
    volumeMounts:
    - name: models
      mountPath: /models
    - name: vector-store
      mountPath: /vector_store
  volumes:
  - name: models
    persistentVolumeClaim:
      claimName: models-pvc
  - name: vector-store
    persistentVolumeClaim:
      claimName: vector-store-pvc