apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.frontend.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.frontend.port }}
          env:
            - name: API_URL
              value: "http://{{ .Release.Name }}-backend:{{ .Values.service.backend.port }}"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.frontend.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Values.frontend.name }} 