apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.nginx.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.nginx.name }}
    spec:
      containers:
        - name: {{ .Values.nginx.name }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.nginx.port }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.nginx.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.service.nginx.type }}
  ports:
    - port: {{ .Values.service.nginx.port }}
      targetPort: {{ .Values.service.nginx.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Values.nginx.name }} 