apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: opt-rag
spec:
  selector:
    app: opt-rag
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: NodePort 