apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: {{ .Release.Name }}-backend
    component: backend
spec:
  type: {{ .Values.services.backend.type }}
  ports:
  - port: {{ .Values.services.backend.port }}
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-backend
    component: backend 