apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: {{ .Release.Name }}-frontend
    component: frontend
spec:
  type: {{ .Values.services.frontend.type }}
  ports:
  - port: {{ .Values.services.frontend.port }}
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-frontend
    component: frontend 