apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: {{ .Release.Name }}-nginx
    component: nginx
spec:
  type: {{ .Values.services.nginx.type }}
  ports:
  - port: {{ .Values.services.nginx.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-nginx
    component: nginx 