apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.models.size }}
  storageClassName: {{ .Values.persistentVolume.models.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vector-store-pvc
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.vectorStore.size }}
  storageClassName: {{ .Values.persistentVolume.vectorStore.storageClass }} 