apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: opt-rag
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;

    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        access_log /var/log/nginx/access.log main;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        gzip on;
        gzip_types text/plain text/css application/json application/javascript;

        server {
            listen 80;
            server_name localhost;

            # API Endpoints - proxy to backend service
            location /api/ {
                proxy_pass http://backend:8000/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # Increased timeouts for LLM processing
                proxy_connect_timeout 30s;
                proxy_send_timeout 120s;
                proxy_read_timeout 300s;  # 5 minutes
            }

            # Forward all other requests to Streamlit
            location / {
                proxy_pass http://frontend:8501/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }

            # Health check endpoint
            location /healthz {
                return 200 'OK';
                add_header Content-Type text/plain;
            }
        }

        # Rate limiting zone definitions
        limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
    } 